### ISSUE TITLE
Rentals page

### ISSUE THREAD

**Issue by jprentals** [cassidyjames/jp-site#6]
- [x] Wording should go as follows: Our speciality is safe and high-quality inflatables such as bounce houses and slides.

- [x] change the order of equipment to : castle, lime castle, sports arena then slide combo and giant slide
 
- [x] we have also decided to list prices next to each item. all 3 of the bounce houses are $200.00. the slide combo is $300.00 and the giant slide is $600.00

- [ ] changing the wording on the following.
    - [x] sports arena: remove (the 15-foot square) insert (This) also correct spelling of footbal to football
    - [x] slide combo: Can't decide between a slide or a bounce house? Choose both with our Slide Combo. The 13 foot bounce castle is attached to an 18 foot long slide, sure to please children of all ages.
    - [x] Castle: The Castle is the perfect classic bounce house option. With four inflated turrets and stylized parapet, children's imaginations will have plenty to play with.
    - [ ] lime castle: Our Lime Castle is a fun bounce house with a bright color scheme, perfect for any party or event.
    - [ ] giant slide: replace (the) with (this) aka This behemoth

**Comment by cassidyjames** [comment]
Do you want the `Dynamic Drop Double Lane Slide` renamed to `Giant Slide` as well?

**Comment by jprentals** [comment]
It can stay as the dynamic drop double lane slide
